# Generated by Django 6.0.7 on 2026-09-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax ID / VAT number. When country is CL this is a Chilean RUT and is validated (modulo-11 check digit), stored as 12.345.678-5.', max_length=50, null=True, verbose_name='Tax ID'),
        ),
    ]
