# Generated by Django 6.0.7 on 2026-09-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_contact_is_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax ID / VAT number. When country is CL this is a Chilean RUT and is validated (modulo-11 check digit), stored as 12.345.678-5.', max_length=50, verbose_name='Tax ID'),
        ),
    ]
