"""Generate a Traefik file-provider config from the active tenant subdomains.

The point is that provisioning a tenant needs no manual step. The operator
console assigns ``Org.subdomain``; a signal (``common.signals``) then rewrites
the file this module produces, and Traefik -- watching that file -- publishes a
router for ``<subdomain>.<base>`` and ``<routing_key>.<base>`` and requests the
certificate for each on first use.

It is a full regeneration from the database every time, not an incremental
edit: idempotent, and it self-heals if the file is lost or drifts. The write is
atomic (temp file + ``os.replace``) so Traefik never reads a half-written file.

Turned off unless ``settings.TRAEFIK_DYNAMIC_FILE`` names a path. A single
shared-host deployment, or one whose Traefik is configured by hand, sets
nothing and this module never touches the filesystem.
"""

from __future__ import annotations

import logging
import os
import tempfile

from django.conf import settings

logger = logging.getLogger(__name__)

_HEADER = (
    "# Generated by common.tenant_routes -- do not edit by hand.\n"
    "# One router per active tenant subdomain; regenerated on every Org change.\n"
)


def _routes_payload():
    """The active ``(router_name, host)`` pairs, subdomain and routing_key both."""
    from common.models import Org

    base = (getattr(settings, "TENANT_BASE_DOMAIN", "") or "").strip().strip(".")
    if not base:
        return []

    pairs = []
    qs = Org.objects.filter(status="ACTIVE").order_by("routing_key")
    for org in qs.only("subdomain", "routing_key"):
        key = org.routing_key
        sub = (org.subdomain or "").strip().lower()
        if sub:
            pairs.append((f"tenant-{key}-sub", f"{sub}.{base}"))
        if key:
            pairs.append((f"tenant-{key}-key", f"{key}.{base}"))
    return pairs


def render_tenant_routes():
    """The Traefik dynamic-config YAML for every active tenant host.

    Hand-rendered rather than dumped through a YAML library: the output is
    small, must stay diff-stable between runs, and carrying a serializer
    dependency for four keys is not worth it.
    """
    service = getattr(settings, "TENANT_ROUTER_SERVICE", "crm-web@docker")
    entrypoint = getattr(settings, "TENANT_ROUTER_ENTRYPOINTS", "websecure")
    certresolver = getattr(settings, "TENANT_ROUTER_CERTRESOLVER", "mytlschallenge")

    pairs = _routes_payload()
    lines = [_HEADER, "http:", "  routers:"]
    if not pairs:
        lines.append("    {}")
    for name, host in pairs:
        lines += [
            f"    {name}:",
            f'      rule: "Host(`{host}`)"',
            f"      service: {service}",
            "      entryPoints:",
            f"        - {entrypoint}",
            "      tls:",
            f"        certResolver: {certresolver}",
        ]
    return "\n".join(lines) + "\n"


def write_tenant_routes():
    """Rewrite ``settings.TRAEFIK_DYNAMIC_FILE`` from the database. No-op if unset.

    Returns the path written, or ``None`` when the feature is off or the write
    fails (a failure is logged, never raised -- an Org save must not 500
    because a sidecar's file could not be updated).
    """
    path = getattr(settings, "TRAEFIK_DYNAMIC_FILE", "") or ""
    if not path:
        return None

    content = render_tenant_routes()
    try:
        directory = os.path.dirname(path) or "."
        os.makedirs(directory, exist_ok=True)
        fd, tmp = tempfile.mkstemp(
            dir=directory, prefix=".tenant-routes-", suffix=".tmp"
        )
        try:
            with os.fdopen(fd, "w") as handle:
                handle.write(content)
            os.replace(tmp, path)
        finally:
            if os.path.exists(tmp):
                os.unlink(tmp)
    except OSError:
        logger.exception("Could not write Traefik tenant routes to %s", path)
        return None
    return path
