# Generated by Django 6.0.7 on 2026-09-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0041_clear_stale_rls_force_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD, Dollar'), ('EUR', 'EUR, Euro'), ('GBP', 'GBP, Pound'), ('INR', 'INR, Rupee'), ('CAD', 'CAD, Dollar'), ('AUD', 'AUD, Dollar'), ('JPY', 'JPY, Yen'), ('CNY', 'CNY, Yuan'), ('CHF', 'CHF, Franc'), ('SGD', 'SGD, Dollar'), ('AED', 'AED, Dirham'), ('BRL', 'BRL, Real'), ('MXN', 'MXN, Peso'), ('CLP', 'CLP, Peso')], default='USD', max_length=3),
        ),
    ]
