# Generated by Django 6.0.7 on 2026-09-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_org_deleted_at_org_routing_key_org_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_operator_access',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
