# Generated by Django 6.0.7 on 2026-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0044_profile_is_operator_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Español')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Español')], default='', max_length=8),
        ),
    ]
