# Generated by Django 6.0.7 on 2026-09-09 01:14

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0045_org_language_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="brand_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex accent colour for emails, e.g. #2563EB.",
                max_length=7,
                validators=[common.validators.validate_hex_color],
            ),
        ),
    ]
