# Generated by Django 6.0.7 on 2026-09-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_lead_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tax_id',
            field=models.CharField(blank=True, default='', help_text='Tax ID / VAT number. Free-form; not validated.', max_length=50, null=True, verbose_name='Tax ID'),
        ),
    ]
